name: "submit"
on: 
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'
      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Build package
        run: npm run build
      - name: Browser Plugin Publish
        uses: plasmo-corp/bpp@v1
        with:
          artifact: ./build/webextension.zip
          keys: ${{ secrets.SUBMIT_KEYS }}
